name: RecipeGraph Roadmap
description: >
  A full-stack personal learning project exploring cloud-native architecture through
  FastAPI, MCP, Helm, Flux, Istio, Prometheus, and Neo4j integration — designed for
  iterative learning, experimentation, and reflection.
public: true

# -------------------------------------
# Custom Fields for Tracking
# -------------------------------------
fields:
  - name: Status
    data_type: single_select
    options:
      - name: 🧩 Backlog
      - name: 🚧 In Progress
      - name: 🕒 Blocked
      - name: ✅ Done

  - name: Difficulty
    data_type: single_select
    options:
      - name: 🟢 Beginner
      - name: 🟡 Intermediate
      - name: 🔴 Advanced

  - name: Focus Area
    data_type: single_select
    options:
      - name: Backend
      - name: DevOps
      - name: Infrastructure
      - name: Observability
      - name: Frontend
      - name: AI / Data
      - name: Documentation

  - name: Estimated Hours
    data_type: number

  - name: Actual Hours
    data_type: number

  - name: Learning Outcome
    data_type: text

views:
  - name: Kanban
    layout: board
    grouped_by: Status

# -------------------------------------
# Items (Phases)
# -------------------------------------
items:
  - title: "Phase 0 — Groundwork"
    body: |
      Establish the project foundation and documentation baseline.
      Deliverables include repo setup, README, decisions log, and quality tools.
    status: 🧩 Backlog
    difficulty: 🟢 Beginner
    focus_area: Infrastructure
    estimated_hours: 5
    learning_outcome: >
      Understand project scaffolding, environment setup, and the discipline of documenting architecture decisions.

  - title: "Phase 1 — Core API & Database"
    body: |
      Implement core CRUD logic for recipes and versions using FastAPI and Postgres.
      Introduce schema design, validation, and testing discipline.
    status: 🧩 Backlog
    difficulty: 🟡 Intermediate
    focus_area: Backend
    estimated_hours: 10
    learning_outcome: >
      Gain fluency in building clean REST APIs, Pydantic validation, and persistence with SQLAlchemy.

  - title: "Phase 2 — MCP Integration"
    body: |
      Expose the API’s capabilities as MCP tools, enabling modular interaction via MCP clients.
    status: 🧩 Backlog
    difficulty: 🟡 Intermediate
    focus_area: Backend
    estimated_hours: 8
    learning_outcome: >
      Learn to expose backend services as modular MCP tools and manage consistent data schemas across components.

  - title: "Phase 3 — Knowledge Graph Integration"
    body: |
      Integrate Neo4j and build a LangGraph pipeline for tagging and relational linking of recipes and ingredients.
    status: 🧩 Backlog
    difficulty: 🔴 Advanced
    focus_area: AI / Data
    estimated_hours: 15
    learning_outcome: >
      Understand graph-based data modeling, relationships, and orchestration through LangGraph pipelines.

  - title: "Phase 4 — Containerization"
    body: |
      Dockerize all services (API, MCP, DBs) and verify reproducible local builds with Compose.
    status: 🧩 Backlog
    difficulty: 🟡 Intermediate
    focus_area: Infrastructure
    estimated_hours: 6
    learning_outcome: >
      Develop practical containerization skills and environment consistency across local systems.

  - title: "Phase 5 — Kubernetes (Local)"
    body: |
      Package services into Helm charts and deploy on a local K8s cluster (MicroK8s or kind).
    status: 🧩 Backlog
    difficulty: 🔴 Advanced
    focus_area: DevOps
    estimated_hours: 12
    learning_outcome: >
      Learn declarative deployment and service discovery within Kubernetes using Helm.

  - title: "Phase 6 — Observability"
    body: |
      Integrate Prometheus metrics and Grafana dashboards for runtime insight.
    status: 🧩 Backlog
    difficulty: 🟡 Intermediate
    focus_area: Observability
    estimated_hours: 6
    learning_outcome: >
      Gain experience in instrumenting applications and visualizing metrics for monitoring.

  - title: "Phase 7 — CI/CD Foundations"
    body: |
      Implement GitHub Actions pipelines for testing, building, and publishing Docker images.
    status: 🧩 Backlog
    difficulty: 🟡 Intermediate
    focus_area: DevOps
    estimated_hours: 5
    learning_outcome: >
      Master basic CI/CD automation using GitHub Actions and container registries.

  - title: "Phase 8 — GitOps (Local Flux)"
    body: |
      Introduce Flux for automated Git-driven deployment to the local cluster.
    status: 🧩 Backlog
    difficulty: 🔴 Advanced
    focus_area: DevOps
    estimated_hours: 10
    learning_outcome: >
      Learn the principles of GitOps and declarative deployment synchronization.

  - title: "Phase 9 — Remote 'Prod' Cluster"
    body: |
      Deploy the app to a single-node k3s cluster on a low-cost VPS and manage via Flux.
    status: 🧩 Backlog
    difficulty: 🔴 Advanced
    focus_area: Infrastructure
    estimated_hours: 8
    learning_outcome: >
      Gain exposure to real-world deployment environments and remote cluster management.

  - title: "Phase 10 — Istio Service Mesh"
    body: |
      Add Istio for ingress, traffic management, and secure service-to-service communication.
    status: 🧩 Backlog
    difficulty: 🔴 Advanced
    focus_area: DevOps
    estimated_hours: 10
    learning_outcome: >
      Learn fundamentals of service meshes and mTLS-based communication security.

  - title: "Phase 11 — Frontend"
    body: |
      Develop a minimal React + Vite interface for recipe creation and visualization.
    status: 🧩 Backlog
    difficulty: 🟡 Intermediate
    focus_area: Frontend
    estimated_hours: 8
    learning_outcome: >
      Build skills in frontend integration and API consumption with a modern toolchain.

  - title: "Phase 12 — Application Metrics"
    body: |
      Define custom business-level metrics and build Grafana dashboards for insights.
    status: 🧩 Backlog
    difficulty: 🟡 Intermediate
    focus_area: Observability
    estimated_hours: 6
    learning_outcome: >
      Understand how to quantify application performance and reliability through metrics.

  - title: "Phase 13 — Optional Flink Streaming"
    body: |
      Introduce Redpanda/Kafka and a Flink job for live ingredient trend computation.
    status: 🧩 Backlog
    difficulty: 🔴 Advanced
    focus_area: AI / Data
    estimated_hours: 12
    learning_outcome: >
      Gain exposure to streaming architectures and distributed computation using Flink.

  - title: "Phase 14 — Hardening & Reliability"
    body: |
      Strengthen configuration management, health probes, and backup routines.
    status: 🧩 Backlog
    difficulty: 🟡 Intermediate
    focus_area: Infrastructure
    estimated_hours: 6
    learning_outcome: >
      Learn production-readiness essentials and system reliability practices.

  - title: "Phase 15 — Knowledge-Driven Enhancements"
    body: |
      Add semantic search, synonym mapping, and LangChain enrichment.
    status: 🧩 Backlog
    difficulty: 🔴 Advanced
    focus_area: AI / Data
    estimated_hours: 8
    learning_outcome: >
      Understand practical applications of lightweight AI enrichment in structured domains.

  - title: "Phase 16 — Presentation & Documentation"
    body: |
      Document architecture, write a demo guide, and create a polished public release.
    status: 🧩 Backlog
    difficulty: 🟢 Beginner
    focus_area: Documentation
    estimated_hours: 4
    learning_outcome: >
      Practice project storytelling and technical documentation for professional visibility.
