"""Recipie tags categorized by type for validation and organization."""

TAGS_BY_CATEGORY: dict[str, set[str]] = {
    "dietary": {
        "vegetarian",
        "vegan",
        "gluten-free",
        "dairy-free",
        "keto",
        "paleo",
        "halal",
        "kosher",
        "low-carb",
        "low-fat",
        "high-protein",
        "nut-free",
        "soy-free",
    },
    "course_type": {
        "appetizer",
        "main",
        "side",
        "dessert",
        "soup",
        "salad",
        "snack",
        "breakfast",
        "brunch",
        "lunch",
        "dinner",
        "drink",
        "sauce",
    },
    "cooking_method": {
        "grilled",
        "baked",
        "fried",
        "roasted",
        "boiled",
        "steamed",
        "stir-fried",
        "slow-cooked",
        "air-fried",
        "raw",
        "poached",
        "seared",
        "smoked",
        "broiled",
        "pressure-cooked",
    },
    "flavor_profile": {
        "spicy",
        "savory",
        "sweet",
        "tangy",
        "smoky",
        "umami",
        "herby",
        "earthy",
        "buttery",
        "zesty",
        "fruity",
        "bitter",
        "creamy",
        "rich",
        "fresh",
    },
    "difficulty": {
        "easy",
        "intermediate",
        "advanced",
        "quick",
        "one-pot",
        "no-cook",
        "30-minutes-or-less",
    },
    "occasion": {
        "holiday",
        "weeknight",
        "summer",
        "winter",
        "fall",
        "spring",
        "comfort-food",
        "meal-prep",
        "budget-friendly",
        "party",
        "kids",
        "date-night",
        "picnic",
        "barbecue",
    },
    "cuisine_types": {
        "american",
        "italian",
        "mexican",
        "japanese",
        "chinese",
        "korean",
        "thai",
        "vietnamese",
        "indian",
        "mediterranean",
        "french",
        "spanish",
        "greek",
        "middle eastern",
        "caribbean",
        "african",
        "ethiopian",
        "moroccan",
        "turkish",
        "german",
        "british",
        "brazilian",
        "argentinian",
        "peruvian",
        "cajun",
        "southern",
        "fusion",
        "seafood",
        "comfort food",
        "street food",
    }
}

# Flatten to a single set for validation
VALID_TAGS: set[str] = set().union(*TAGS_BY_CATEGORY.values())
